/**
 * generated by Xtext 2.26.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Let#getName <em>Name</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Let#getLetExp <em>Let Exp</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Let#getInExp <em>In Exp</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLet()
 * @model
 * @generated
 */
public interface Let extends Primary
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLet_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Let#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Let Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Let Exp</em>' containment reference.
   * @see #setLetExp(Exp)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLet_LetExp()
   * @model containment="true"
   * @generated
   */
  Exp getLetExp();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Let#getLetExp <em>Let Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Let Exp</em>' containment reference.
   * @see #getLetExp()
   * @generated
   */
  void setLetExp(Exp value);

  /**
   * Returns the value of the '<em><b>In Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>In Exp</em>' containment reference.
   * @see #setInExp(Exp)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLet_InExp()
   * @model containment="true"
   * @generated
   */
  Exp getInExp();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Let#getInExp <em>In Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In Exp</em>' containment reference.
   * @see #getInExp()
   * @generated
   */
  void setInExp(Exp value);

} // Let
